### ISSUE TITLE
ad_integration_sssd_custom_settings causes additional section in sssd.conf when domainname is not lowercase in AD

### ISSUE THREAD

**Issue by Dennis-Q** [linux-system-roles/ad_integration#142]
In our environment, using this role, we noticed some strange behavior when handling additional custom settings for the domain.

To be more specific, the AD that we connect to is called COMPANY.CORP.
The vars we use (in addition to the credentials):
```
  ad_integration_realm: company.corp
  ad_integration_auto_id_mapping: false
  ad_integration_computer_ou: "ou=ServersLinux,ou=computers,dc=domain,dc=corp"
  ad_integration_client_software: sssd
  ad_integration_membership_software: adcli
  ad_integration_sssd_custom_settings:
  - key: "default_shell"
    value: "/bin/sh"
```
Yes, the ad_integration_realm is really lowercase. But inside the AD, it actually is uppercase. 

Without the 'ad_integration_sssd_custom_settings' it results in:
```
[sssd]
domains = COMPANY.CORP
config_file_version = 2
services = nss, pam
ad_enabled_domains = company.corp

[domain/COMPANY.CORP]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = COMPANY.CORP
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u@%d
ad_domain = COMPANY.CORP
use_fully_qualified_names = True
ldap_id_mapping = False
access_provider = ad
```

However, when `ad_integration_sssd_custom_settings` variable is provided like above, it creates an additional section in our case:

```
[sssd]
domains = COMPANY.CORP
config_file_version = 2
services = nss, pam
ad_enabled_domains = company.corp

[domain/COMPANY.CORP]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = COMPANY.CORP
realmd_tags = manages-system joined-with-adcli
id_provider = ad
fallback_homedir = /home/%u@%d
ad_domain = COMPANY.CORP
use_fully_qualified_names = True
ldap_id_mapping = False
access_provider = ad
[domain/company.corp]
default_shell = /bin/bash
ldap_group_name = sAMAccountName
override_homedir = /home/%d/%u
use_fully_qualified_names = False
auto_private_groups = True
subdomains_provider = none
ldap_user_extra_attrs = altSecurityIdentities
ldap_user_ssh_public_key = altSecurityIdentities
ldap_use_tokengroups = False
ad_enable_gc = False
ad_gpo_access_control = Disabled
```

So I understand this is partly caused by the fact that the name is configured (within the AD) in capitals by the Windows team when it was initially setup, but this is not something that we can change anymore. This seems to be caused by an assumption that this section is always lower-case which obviously isn't always the case. To be more specific:
https://github.com/linux-system-roles/ad_integration/blob/main/tasks/main.yml#L262

It probably also is wrong in these places:
https://github.com/linux-system-roles/ad_integration/blob/main/tasks/main.yml#L220
and
https://github.com/linux-system-roles/ad_integration/blob/main/tasks/main.yml#L279

(I haven't checked the full role but these are the ones I found in main.yml.)

\
**Is it possible to remove the '| lower'?**
