### ISSUE TITLE
Add support for Rocky

### ISSUE THREAD

**Issue by MikeCantCode** [linux-system-roles/ad_integration#39]
There are some conditonals that filter out Rocky distributions. [Here](https://github.com/linux-system-roles/ad_integration/blob/main/tasks/main.yml#LL112C55-L112C55) and [here](https://github.com/linux-system-roles/ad_integration/blob/main/tasks/main.yml#L124) for example.

Adding `Rocky` to these conditionals would suffice.

``` yaml
- name: Manage crypto policies
  include_role:
    name: fedora.linux_system_roles.crypto_policies
  vars:
    crypto_policies_policy: "DEFAULT:AD-SUPPORT"
  when:
    - ad_integration_manage_crypto_policies | bool
    # Fedora and RHEL8+
    - (ansible_distribution == "Fedora" or
      (ansible_distribution in ['CentOS', 'RedHat', 'Rocky'] and
       ansible_distribution_version is version('8', '>=')))
```
